import { UserProfile, Stream, ChatMessage, Category } from '@/lib/types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat_all', name: 'All', slug: 'all' },
  { id: 'cat_music', name: 'Music', slug: 'music' },
  { id: 'cat_gaming', name: 'Gaming', slug: 'gaming' },
  { id: 'cat_chatting', name: 'Just Chatting', slug: 'just-chatting' },
  { id: 'cat_dance', name: 'Dance', slug: 'dance' },
  { id: 'cat_art', name: 'Art', slug: 'art' },
  { id: 'cat_fitness', name: 'Fitness', slug: 'fitness' },
  { id: 'cat_outdoors', name: 'Outdoors', slug: 'outdoors' },
  { id: 'cat_lifestyle', name: 'Lifestyle', slug: 'lifestyle' },
  { id: 'cat_tech', name: 'Tech', slug: 'tech' },
];

export const MOCK_CREATORS: (UserProfile & { verified?: boolean; followersCount?: number; isFollowing?: boolean })[] = [
  {
    id: 'creator_001',
    email: 'aria@zylo.live',
    username: 'ariamorgan',
    displayName: 'Aria Morgan',
    role: 'CREATOR',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop',
    verified: true,
    followersCount: 42500,
    profile: {
      bio: 'Music creator & acoustic singer ✨ Sharing warm night vibes & song requests.',
      location: 'London, UK',
    },
    _count: { followers: 42500, following: 120, streams: 48 },
  },
  {
    id: 'creator_002',
    email: 'karan@zylo.live',
    username: 'karanmehta',
    displayName: 'Karan Mehta',
    role: 'CREATOR',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&auto=format&fit=crop',
    verified: true,
    followersCount: 88200,
    profile: {
      bio: 'Competitive Valorant & FPS strategist 🎮 Pushing ranks daily.',
      location: 'Austin, TX',
    },
    _count: { followers: 88200, following: 95, streams: 112 },
  },
  {
    id: 'creator_003',
    email: 'mei@zylo.live',
    username: 'meit',
    displayName: 'Mei Tanaka',
    role: 'CREATOR',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop',
    verified: true,
    followersCount: 31000,
    profile: {
      bio: 'Digital illustrator & 3D concept artist 🎨 Painting live and taking Q&A.',
      location: 'Tokyo, Japan',
    },
    _count: { followers: 31000, following: 210, streams: 64 },
  },
  {
    id: 'creator_004',
    email: 'lina@zylo.live',
    username: 'linab',
    displayName: 'Lina Brooks',
    role: 'CREATOR',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&auto=format&fit=crop',
    verified: true,
    followersCount: 56400,
    profile: {
      bio: 'Late night chats, coffee talk & cozy community vibes ☕',
      location: 'Seattle, WA',
    },
    _count: { followers: 56400, following: 340, streams: 85 },
  },
  {
    id: 'creator_005',
    email: 'alex@zylo.live',
    username: 'alexoutdoors',
    displayName: 'Alex Carter',
    role: 'CREATOR',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop',
    verified: true,
    followersCount: 29800,
    profile: {
      bio: 'Outdoor adventure & mountain trail runner 🏔️ Streaming live from nature.',
      location: 'Denver, CO',
    },
    _count: { followers: 29800, following: 88, streams: 39 },
  },
  {
    id: 'creator_006',
    email: 'rhea@zylo.live',
    username: 'rheafit',
    displayName: 'Rhea Kapoor',
    role: 'CREATOR',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop',
    verified: true,
    followersCount: 64100,
    profile: {
      bio: 'Certified athletic trainer & HIIT mobility coach 💪 Train together daily.',
      location: 'Miami, FL',
    },
    _count: { followers: 64100, following: 145, streams: 92 },
  },
  {
    id: 'creator_007',
    email: 'kabir@zylo.live',
    username: 'kabirbeats',
    displayName: 'Kabir Sharma',
    role: 'CREATOR',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop',
    verified: true,
    followersCount: 19300,
    profile: {
      bio: 'Lo-fi beatmaker & live synthesizer improvisor 🎧 Late night jams.',
      location: 'Mumbai, India',
    },
    _count: { followers: 19300, following: 160, streams: 27 },
  },
  {
    id: 'creator_008',
    email: 'noah@zylo.live',
    username: 'noahcreates',
    displayName: 'Noah Williams',
    role: 'CREATOR',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop',
    verified: true,
    followersCount: 73500,
    profile: {
      bio: 'Fullstack engineer & open-source AI builder 💻 Building real-time apps live.',
      location: 'San Francisco, CA',
    },
    _count: { followers: 73500, following: 280, streams: 105 },
  },
  {
    id: 'creator_009',
    email: 'sophie@zylo.live',
    username: 'sophiedance',
    displayName: 'Sophie Reed',
    role: 'CREATOR',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&auto=format&fit=crop',
    verified: false,
    followersCount: 51200,
    profile: {
      bio: 'Choreographer & freestyle urban dancer 💃 High energy studio sessions.',
      location: 'Los Angeles, CA',
    },
    _count: { followers: 51200, following: 175, streams: 74 },
  },
  {
    id: 'creator_010',
    email: 'ethan@zylo.live',
    username: 'ethanblake',
    displayName: 'Ethan Blake',
    role: 'CREATOR',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=500&auto=format&fit=crop',
    verified: false,
    followersCount: 38900,
    profile: {
      bio: 'RPG speedrunner & retro arcade archivist 👾',
      location: 'Chicago, IL',
    },
    _count: { followers: 38900, following: 110, streams: 63 },
  },
  {
    id: 'creator_011',
    email: 'ava@zylo.live',
    username: 'avamartinez',
    displayName: 'Ava Martinez',
    role: 'CREATOR',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop',
    verified: true,
    followersCount: 47600,
    profile: {
      bio: 'Mindful living, interior aesthetics & morning routine streams 🌿',
      location: 'New York, NY',
    },
    _count: { followers: 47600, following: 205, streams: 58 },
  },
  {
    id: 'creator_012',
    email: 'vikram@zylo.live',
    username: 'vikramsingh',
    displayName: 'Vikram Singh',
    role: 'CREATOR',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop',
    verified: true,
    followersCount: 22400,
    profile: {
      bio: 'Tech hardware tear-downs & custom PC builds 🛠️',
      location: 'Bengaluru, India',
    },
    _count: { followers: 22400, following: 92, streams: 31 },
  },
];

export const MOCK_STREAMS: Stream[] = [
  // 12 LIVE Streams
  {
    id: 'stream_001',
    broadcasterId: 'creator_001',
    broadcaster: MOCK_CREATORS[0],
    title: 'Chill Night Vibes ✨',
    description: 'Acoustic songs, warm lighting & chill conversation with everyone!',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop',
    status: 'LIVE',
    viewerCount: 3200,
    peakViewerCount: 3890,
    category: { id: 'cat_music', name: 'Music', slug: 'music' },
    tags: ['Music', 'Acoustic', 'Chill', 'Late Night'],
    vibe: 'Music',
    startedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_002',
    broadcasterId: 'creator_002',
    broadcaster: MOCK_CREATORS[1],
    title: 'Rank Push to Radiant 🎮',
    description: 'High level FPS gameplay, tactical callouts and viewer games.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop',
    status: 'LIVE',
    viewerCount: 2400,
    peakViewerCount: 2800,
    category: { id: 'cat_gaming', name: 'Gaming', slug: 'gaming' },
    tags: ['Gaming', 'Esports', 'Ranked', 'Competitive'],
    vibe: 'Gaming',
    startedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_003',
    broadcasterId: 'creator_003',
    broadcaster: MOCK_CREATORS[2],
    title: 'Fantasy Concept Art Workshop 🎨',
    description: 'Digital painting session live on tablet. Working on character designs!',
    thumbnailUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&auto=format&fit=crop',
    status: 'LIVE',
    viewerCount: 1800,
    peakViewerCount: 2100,
    category: { id: 'cat_art', name: 'Art', slug: 'art' },
    tags: ['Art', 'Illustration', 'Digital Art', 'Design'],
    vibe: 'Art',
    startedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_004',
    broadcasterId: 'creator_004',
    broadcaster: MOCK_CREATORS[3],
    title: 'Late Night Coffee & Cozy Talks ☕',
    description: 'Grab a hot mug and drop in. Answering viewer questions & story time.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&auto=format&fit=crop',
    status: 'LIVE',
    viewerCount: 1420,
    peakViewerCount: 1650,
    category: { id: 'cat_chatting', name: 'Just Chatting', slug: 'just-chatting' },
    tags: ['Just Chatting', 'Cozy', 'Q&A', 'Community'],
    vibe: 'Just Chatting',
    startedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_005',
    broadcasterId: 'creator_005',
    broadcaster: MOCK_CREATORS[4],
    title: 'Himalayan Ridge Trek Live 🏔️',
    description: 'Live mountain summit trail broadcast with crisp alpine weather.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&auto=format&fit=crop',
    status: 'LIVE',
    viewerCount: 980,
    peakViewerCount: 1200,
    category: { id: 'cat_outdoors', name: 'Outdoors', slug: 'outdoors' },
    tags: ['Outdoors', 'Hiking', 'Nature', 'Travel'],
    vibe: 'Outdoors',
    startedAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_006',
    broadcasterId: 'creator_006',
    broadcaster: MOCK_CREATORS[5],
    title: 'Full-Body HIIT & Core Workout 💪',
    description: 'High intensity mobility & bodyweight workout session. Train with me!',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=1200&auto=format&fit=crop',
    status: 'LIVE',
    viewerCount: 780,
    peakViewerCount: 910,
    category: { id: 'cat_fitness', name: 'Fitness', slug: 'fitness' },
    tags: ['Fitness', 'Workout', 'HIIT', 'Health'],
    vibe: 'Fitness',
    startedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_007',
    broadcasterId: 'creator_007',
    broadcaster: MOCK_CREATORS[6],
    title: 'Midnight Lo-Fi Beatmaking Session 🎧',
    description: 'Live analog synthesizer jam, lo-fi drum chops & chill soundscapes.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=1200&auto=format&fit=crop',
    status: 'LIVE',
    viewerCount: 920,
    peakViewerCount: 1100,
    category: { id: 'cat_music', name: 'Music', slug: 'music' },
    tags: ['Music', 'LoFi', 'Beats', 'Producer'],
    vibe: 'Music',
    startedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_008',
    broadcasterId: 'creator_008',
    broadcaster: MOCK_CREATORS[7],
    title: 'Building AI Agents in Real Time 💻',
    description: 'Live coding: building real-time vector search & agentic workflow with Next.js.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&auto=format&fit=crop',
    status: 'LIVE',
    viewerCount: 1150,
    peakViewerCount: 1400,
    category: { id: 'cat_tech', name: 'Tech', slug: 'tech' },
    tags: ['Tech', 'Coding', 'AI', 'Fullstack'],
    vibe: 'Tech',
    startedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_009',
    broadcasterId: 'creator_009',
    broadcaster: MOCK_CREATORS[8],
    title: 'Neon Street Dance Session 💃',
    description: 'Choreographed live session featuring urban street dance & electronic beats.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&auto=format&fit=crop',
    status: 'LIVE',
    viewerCount: 640,
    peakViewerCount: 750,
    category: { id: 'cat_dance', name: 'Dance', slug: 'dance' },
    tags: ['Dance', 'Choreography', 'Urban', 'Studio'],
    vibe: 'Dance',
    startedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_010',
    broadcasterId: 'creator_010',
    broadcaster: MOCK_CREATORS[9],
    title: 'Elden Ring No-Hit Speedrun 👾',
    description: 'Attempting a clean boss rush run. Come cheer in chat!',
    thumbnailUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&auto=format&fit=crop',
    status: 'LIVE',
    viewerCount: 510,
    peakViewerCount: 620,
    category: { id: 'cat_gaming', name: 'Gaming', slug: 'gaming' },
    tags: ['Gaming', 'Speedrun', 'Hardcore', 'Challenge'],
    vibe: 'Gaming',
    startedAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_011',
    broadcasterId: 'creator_011',
    broadcaster: MOCK_CREATORS[10],
    title: 'Sunset Apartment Makeover & Decor 🌿',
    description: 'Rearranging the studio space, vintage plant styling & warm lighting setup.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&auto=format&fit=crop',
    status: 'LIVE',
    viewerCount: 830,
    peakViewerCount: 950,
    category: { id: 'cat_lifestyle', name: 'Lifestyle', slug: 'lifestyle' },
    tags: ['Lifestyle', 'Decor', 'Vlog', 'Aesthetic'],
    vibe: 'Lifestyle',
    startedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_012',
    broadcasterId: 'creator_012',
    broadcaster: MOCK_CREATORS[11],
    title: 'Custom Liquid-Cooled PC Build 🛠️',
    description: 'Assembling a dual-GPU workstation live. Tube bending & cable management.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=1200&auto=format&fit=crop',
    status: 'LIVE',
    viewerCount: 690,
    peakViewerCount: 810,
    category: { id: 'cat_tech', name: 'Tech', slug: 'tech' },
    tags: ['Tech', 'PC Building', 'Hardware', 'Custom'],
    vibe: 'Tech',
    startedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
  } as any,

  // 6 SCHEDULED Streams
  {
    id: 'stream_013',
    broadcasterId: 'creator_012',
    broadcaster: MOCK_CREATORS[11],
    title: 'Next-Gen GPU Deep Dive & Benchmark 🛠️',
    description: 'Live testing the latest workstation graphics cards and architecture.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=1200&auto=format&fit=crop',
    status: 'SCHEDULED',
    viewerCount: 0,
    scheduledAt: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    category: { id: 'cat_tech', name: 'Tech', slug: 'tech' },
    tags: ['Tech', 'Hardware', 'Benchmarks'],
    vibe: 'Tech',
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_014',
    broadcasterId: 'creator_003',
    broadcaster: MOCK_CREATORS[2],
    title: 'Portrait Oil Painting Masterclass 🖌️',
    description: 'Step by step color mixing, canvas priming and digital texture techniques.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1200&auto=format&fit=crop',
    status: 'SCHEDULED',
    viewerCount: 0,
    scheduledAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    category: { id: 'cat_art', name: 'Art', slug: 'art' },
    tags: ['Art', 'Painting', 'Tutorial'],
    vibe: 'Art',
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_015',
    broadcasterId: 'creator_009',
    broadcaster: MOCK_CREATORS[8],
    title: 'Ballet & Flexibility Masterclass 🩰',
    description: 'Choreography breakdown and mobility drills for dancers of all levels.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=1200&auto=format&fit=crop',
    status: 'SCHEDULED',
    viewerCount: 0,
    scheduledAt: new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString(),
    category: { id: 'cat_dance', name: 'Dance', slug: 'dance' },
    tags: ['Dance', 'Ballet', 'Fitness'],
    vibe: 'Dance',
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_016',
    broadcasterId: 'creator_006',
    broadcaster: MOCK_CREATORS[5],
    title: 'Deadlift Technique & Max Out Session 🏋️',
    description: 'Form check, bracing mechanics and heavy lifting with chat commentary.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&auto=format&fit=crop',
    status: 'SCHEDULED',
    viewerCount: 0,
    scheduledAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    category: { id: 'cat_fitness', name: 'Fitness', slug: 'fitness' },
    tags: ['Fitness', 'Powerlifting', 'Training'],
    vibe: 'Fitness',
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_017',
    broadcasterId: 'creator_005',
    broadcaster: MOCK_CREATORS[4],
    title: 'Sunset Trail Run in Patagonia 🏃',
    description: 'Broadcasting live from South American wilderness paths.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1200&auto=format&fit=crop',
    status: 'SCHEDULED',
    viewerCount: 0,
    scheduledAt: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    category: { id: 'cat_outdoors', name: 'Outdoors', slug: 'outdoors' },
    tags: ['Outdoors', 'TrailRun', 'Travel'],
    vibe: 'Outdoors',
    createdAt: new Date().toISOString(),
  } as any,
  {
    id: 'stream_018',
    broadcasterId: 'creator_007',
    broadcaster: MOCK_CREATORS[6],
    title: 'Acoustic Piano & Lo-Fi Jam 🎹',
    description: 'Relaxing piano progressions, warm reverb & late night lounge vibes.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=1200&auto=format&fit=crop',
    status: 'SCHEDULED',
    viewerCount: 0,
    scheduledAt: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
    category: { id: 'cat_music', name: 'Music', slug: 'music' },
    tags: ['Music', 'Piano', 'LoFi'],
    vibe: 'Music',
    createdAt: new Date().toISOString(),
  } as any,
];

export const MOCK_CHAT_MESSAGES: Record<string, ChatMessage[]> = {
  stream_001: [
    {
      id: 'm1',
      streamId: 'stream_001',
      userId: 'c_user_1',
      message: 'such a vibe! 💜',
      createdAt: new Date(Date.now() - 50000).toISOString(),
      user: { id: 'c_user_1', username: 'aarav', displayName: 'Aarav', avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop' },
    },
    {
      id: 'm2',
      streamId: 'stream_001',
      userId: 'c_user_2',
      message: 'love this song 🔥',
      createdAt: new Date(Date.now() - 40000).toISOString(),
      user: { id: 'c_user_2', username: 'simran', displayName: 'Simran', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop' },
    },
    {
      id: 'm3',
      streamId: 'stream_001',
      userId: 'c_user_3',
      message: 'from where is this track?',
      createdAt: new Date(Date.now() - 30000).toISOString(),
      user: { id: 'c_user_3', username: 'rohit', displayName: 'Rohit', avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop' },
    },
    {
      id: 'm4',
      streamId: 'stream_001',
      userId: 'c_user_4',
      message: 'amazing ✨',
      createdAt: new Date(Date.now() - 20000).toISOString(),
      user: { id: 'c_user_4', username: 'isha', displayName: 'Isha', avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop' },
    },
    {
      id: 'm5',
      streamId: 'stream_001',
      userId: 'c_user_5',
      message: 'can you drop the playlist?',
      createdAt: new Date(Date.now() - 10000).toISOString(),
      user: { id: 'c_user_5', username: 'karan', displayName: 'Karan', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop' },
    },
  ],
};
